/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void nameFieldChange(GTextField source, GEvent event) { //_CODE_:nameField:851807:
    if (event.equals(GEvent.ENTERED)) {
        writeText("data/Name.txt", new String[]{source.getText()});
        getUsername();
        nameLabel.text = new String[]{"Hi, " + name};
        source.setText("");
        nameFieldVisible = false;
        source.setVisible(nameFieldVisible);
    }
} //_CODE_:nameField:851807:

public void chatFieldChange(GTextField source, GEvent event) { //_CODE_:chatField:897872:
    if (event.equals(GEvent.ENTERED)) {
        sendMessage(source.getText());
        source.setText("");
    }
} //_CODE_:chatField:897872:

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
    G4P.messagesEnabled(false);
    G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
    G4P.setCursor(ARROW);
    surface.setTitle("Sketch Window");
    nameField = new GTextField(this, PADDING, nameLabel.size.y + 2 * PADDING, nameLabel.size.x, nameLabel.size.y, G4P.SCROLLBARS_NONE);
    nameField.setFont(new Font("Dialog", Font.PLAIN, 14));
    nameField.setLocalColorScheme(GCScheme.GOLD_SCHEME);
    nameField.setOpaque(true);
    nameField.addEventHandler(this, "nameFieldChange");
    nameField.setVisible(nameFieldVisible);
    chatField = new GTextField(this, PADDING, height - PADDING - 26, weekPanel.size.x, 26, G4P.SCROLLBARS_NONE);
    chatField.setFont(new Font("Dialog", Font.PLAIN, 14));
    chatField.setLocalColorScheme(GCScheme.GOLD_SCHEME);
    chatField.setOpaque(true);
    chatField.addEventHandler(this, "chatFieldChange");
}

// Variable declarations 
// autogenerated do not edit
GTextField nameField;
GTextField chatField;
